import "@/src/components/styles/globals.css";
import Head from "next/head";
import React from "react";

function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Beli.id</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default App;